// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0GREVoKUEtb2DESbROo-0pJV4k1dJsAA',
    appId: '1:939198105430:web:1a6e123ad360ed967478f7',
    messagingSenderId: '939198105430',
    projectId: 'tnp-portal-63ea2',
    authDomain: 'tnp-portal-63ea2.firebaseapp.com',
    databaseURL: 'https://tnp-portal-63ea2-default-rtdb.firebaseio.com',
    storageBucket: 'tnp-portal-63ea2.appspot.com',
    measurementId: 'G-R42ND30XHJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxvR00RO_ExkORvoCJe7MkfwnO269WRM8',
    appId: '1:939198105430:android:9bb4b5a1230865047478f7',
    messagingSenderId: '939198105430',
    projectId: 'tnp-portal-63ea2',
    databaseURL: 'https://tnp-portal-63ea2-default-rtdb.firebaseio.com',
    storageBucket: 'tnp-portal-63ea2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGdp_HI3URdHBq9ItK66oVmOQNK03ChHE',
    appId: '1:939198105430:ios:a17f09ff6fc4342d7478f7',
    messagingSenderId: '939198105430',
    projectId: 'tnp-portal-63ea2',
    databaseURL: 'https://tnp-portal-63ea2-default-rtdb.firebaseio.com',
    storageBucket: 'tnp-portal-63ea2.appspot.com',
    iosBundleId: 'com.example.tnpPortal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGdp_HI3URdHBq9ItK66oVmOQNK03ChHE',
    appId: '1:939198105430:ios:a17f09ff6fc4342d7478f7',
    messagingSenderId: '939198105430',
    projectId: 'tnp-portal-63ea2',
    databaseURL: 'https://tnp-portal-63ea2-default-rtdb.firebaseio.com',
    storageBucket: 'tnp-portal-63ea2.appspot.com',
    iosBundleId: 'com.example.tnpPortal',
  );
}
